version: "3"
services:
  postgres:
        container_name: postgres
        image: registry.cn-hangzhou.aliyuncs.com/snaplingo/game-db:1.0
        container_name: test-pg    
        volumes:
            - /tmp/pgdata:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1234qwer!@#$$QWER
        expose:
            - "5432"
        ports:
            - "5432:5432"
