development:
  mysql:
    host: 127.0.0.1:3306
    dbname: game
    username: root
    password: 123456
    #password: password
    maxOpenConns: 1000
    maxIdleConns: 200
    connMaxLifetime: 5
  env:
    env: development-env
  cfg:
    token: aed743c9-a398-4f00-9f54-c2f0599be29e
    port: 8080
    timeZone: Asia/Shanghai
  redis:
     host: 127.0.0.1:6379
     password:
     db: 0
test:
  mysql:
    host: 127.0.0.1:3306
    dbname: game
    username: root
    password: password
    maxOpenConns: 1000
    maxIdleConns: 200
    connMaxLifetime: 5
  env:
    env: test-env
  cfg:
    token: aed743c9-a398-4f00-9f54-c2f0599be29e
    port: 8080
    timeZone: Asia/Shanghai
  redis:
    host: 127.0.0.1:6379
    password:
    db: 0
production:
  mysql:
    host: 127.0.0.1:8980
    dbname: self_game
    username: mn01
    password: 123456
    maxOpenConns: 1000
    maxIdleConns: 200
    connMaxLifetime: 5
  env:
    env: production-env
  cfg:
    token: aed743c9-a398-4f00-9f54-c2f0599be29f
    port: 8080
    timeZone: America/Los_Angeles
  redis:
    host: 127.0.0.1:6379
    password:
    db: 0